### ISSUE TITLE
DataFrame Test Fails

### ISSUE THREAD

**Issue by TheChymera** [ArcasProject/Arcas#38]
Even on Python3.4, at least one of the tests still fails:

```
 * Fetching https://github.com/ArcasProject/Arcas ...
git fetch https://github.com/ArcasProject/Arcas +HEAD:refs/git-r3/HEAD
git symbolic-ref refs/git-r3/sci-libs/arcas/0/__main__ refs/git-r3/HEAD
 * Checking out https://github.com/ArcasProject/Arcas to /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999 ...
git checkout --quiet refs/git-r3/HEAD
GIT update -->
   repository:               https://github.com/ArcasProject/Arcas
   at the commit:            88d6480dd5d5410298ca60b8acfbfe95b661bd50
>>> Source unpacked in /var/tmp/portage/sci-libs/arcas-9999/work
>>> Preparing source in /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999 ...
 * python3_4: running distutils-r1_run_phase distutils-r1_python_compile
/usr/bin/python3.4 setup.py build
running build
running build_py
creating /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999-python3_4/lib/arcas
copying src/arcas/__init__.py -> /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999-python3_4/lib/arcas
copying src/arcas/version.py -> /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999-python3_4/lib/arcas
copying src/arcas/tools.py -> /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999-python3_4/lib/arcas
creating /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999-python3_4/lib/arcas/IEEE
copying src/arcas/IEEE/__init__.py -> /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999-python3_4/lib/arcas/IEEE
copying src/arcas/IEEE/main.py -> /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999-python3_4/lib/arcas/IEEE
creating /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999-python3_4/lib/arcas/arXiv
copying src/arcas/arXiv/__init__.py -> /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999-python3_4/lib/arcas/arXiv
copying src/arcas/arXiv/main.py -> /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999-python3_4/lib/arcas/arXiv
creating /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999-python3_4/lib/arcas/Springer
copying src/arcas/Springer/__init__.py -> /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999-python3_4/lib/arcas/Springer
copying src/arcas/Springer/main.py -> /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999-python3_4/lib/arcas/Springer
copying src/arcas/Springer/api_key.py -> /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999-python3_4/lib/arcas/Springer
creating /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999-python3_4/lib/arcas/PLOS
copying src/arcas/PLOS/__init__.py -> /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999-python3_4/lib/arcas/PLOS
copying src/arcas/PLOS/main.py -> /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999-python3_4/lib/arcas/PLOS
creating /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999-python3_4/lib/arcas/nature
copying src/arcas/nature/__init__.py -> /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999-python3_4/lib/arcas/nature
copying src/arcas/nature/main.py -> /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999-python3_4/lib/arcas/nature
warning: build_py: byte-compiling is disabled, skipping.

running build_scripts
creating /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999-python3_4/scripts
copying and adjusting bin/arcas_scrape -> /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999-python3_4/scripts
changing mode of /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999-python3_4/scripts/arcas_scrape from 644 to 755
>>> Source compiled.
>>> Test phase: sci-libs/arcas-9999
 * python3_4: running distutils-r1_run_phase python_test
running test
running egg_info
creating src/arcas.egg-info
writing dependency_links to src/arcas.egg-info/dependency_links.txt
writing requirements to src/arcas.egg-info/requires.txt
writing src/arcas.egg-info/PKG-INFO
writing top-level names to src/arcas.egg-info/top_level.txt
writing manifest file 'src/arcas.egg-info/SOURCES.txt'
writing manifest file 'src/arcas.egg-info/SOURCES.txt'
running build_ext
running test
running egg_info
writing dependency_links to src/arcas.egg-info/dependency_links.txt
writing requirements to src/arcas.egg-info/requires.txt
writing src/arcas.egg-info/PKG-INFO
writing top-level names to src/arcas.egg-info/top_level.txt
writing manifest file 'src/arcas.egg-info/SOURCES.txt'
running build_ext
test_create_keys (tests.TestTools) ... ok
test_create_url (tests.TestTools) ... ok
test_requests (tests.TestTools) ... ok
test_validate (tests.TestTools) ... ok
test_xml_to_dict (tests.TestTools) ... ok
test_keys (tests_arxiv.TestArxiv) ... ok
test_parameters (tests_arxiv.TestArxiv) ... ok
test_to_json (tests_arxiv.TestArxiv) ... /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999/tests/tests_arxiv.py:52: HypothesisDeprecationWarning: Using example() inside a test function is a bad idea. It will become an error in a future version of Hypothesis, but it's unlikely that it's doing what you intend even now. Instead consider using hypothesis.strategies.data() to draw more examples during testing. See https://hypothesis.readthedocs.io/en/latest/data.html#drawing-interactively-in-tests for more details.
  a_date = dates(min_year=1000, max_year=2017).example()
/usr/lib64/python3.4/site-packages/hypothesis/searchstrategy/lazy.py:121: HypothesisDeprecationWarning: Use hypothesis.strategies.dates, which supports bounds given as date objects for single-day resolution.
  *self.__args, **self.__kwargs
ok
test_keys (tests_ieee.TestIEEE) ... ok
test_parameters (tests_ieee.TestIEEE) ... ok
test_to_dataframe (tests_ieee.TestIEEE) ... FAIL
test_keys (tests_nature.TestNature) ... ok
test_parameters (tests_nature.TestNature) ... ok
test_to_json (tests_nature.TestNature) ... /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999/tests/tests_nature.py:52: HypothesisDeprecationWarning: Using example() inside a test function is a bad idea. It will become an error in a future version of Hypothesis, but it's unlikely that it's doing what you intend even now. Instead consider using hypothesis.strategies.data() to draw more examples during testing. See https://hypothesis.readthedocs.io/en/latest/data.html#drawing-interactively-in-tests for more details.
  a_date = dates(min_year=1000, max_year=2017).example()
ok
test_keys (tests_plos.TestArxiv) ... ok
test_parameters (tests_plos.TestArxiv) ... ok
test_to_dataframe (tests_plos.TestArxiv) ... /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999/tests/tests_plos.py:45: HypothesisDeprecationWarning: Using example() inside a test function is a bad idea. It will become an error in a future version of Hypothesis, but it's unlikely that it's doing what you intend even now. Instead consider using hypothesis.strategies.data() to draw more examples during testing. See https://hypothesis.readthedocs.io/en/latest/data.html#drawing-interactively-in-tests for more details.
  a_date = dates(min_year=1000, max_year=2017).example()
ok
test_keys (tests_springer.TestSpinger) ... ok
test_parameters (tests_springer.TestSpinger) ... ok
test_to_json (tests_springer.TestSpinger) ... /var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999/tests/tests_springer.py:51: HypothesisDeprecationWarning: Using example() inside a test function is a bad idea. It will become an error in a future version of Hypothesis, but it's unlikely that it's doing what you intend even now. Instead consider using hypothesis.strategies.data() to draw more examples during testing. See https://hypothesis.readthedocs.io/en/latest/data.html#drawing-interactively-in-tests for more details.
  a_date = dates(min_year=1000, max_year=2017).example()
ok
/var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999/README.md
Doctest: README.md ... ok

======================================================================
FAIL: test_to_dataframe (tests_ieee.TestIEEE)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999/tests/tests_ieee.py", line 51, in test_to_dataframe
    def test_to_dataframe(self, entry):
  File "/usr/lib64/python3.4/site-packages/hypothesis/core.py", line 1008, in wrapped_test
    state.run()
  File "/usr/lib64/python3.4/site-packages/hypothesis/core.py", line 846, in run
    print_example=True, is_final=True
  File "/usr/lib64/python3.4/site-packages/hypothesis/executors.py", line 58, in default_new_style_executor
    return function(data)
  File "/usr/lib64/python3.4/site-packages/hypothesis/core.py", line 140, in run
    return test(*args, **kwargs)
  File "/var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999/tests/tests_ieee.py", line 51, in test_to_dataframe
    def test_to_dataframe(self, entry):
  File "/usr/lib64/python3.4/site-packages/hypothesis/core.py", line 591, in timed_test
    result = test(*args, **kwargs)
  File "/var/tmp/portage/sci-libs/arcas-9999/work/arcas-9999/tests/tests_ieee.py", line 70, in test_to_dataframe
    ','))
AssertionError: Lists differ: ['', '0000_ 00000_ 00000_ 00000_ 0000'] != ['', '0000_ 00000_ 00000_ 00000_ 0000', '']

Second list contains 1 additional elements.
First extra element 2:


- ['', '0000_ 00000_ 00000_ 00000_ 0000']
+ ['', '0000_ 00000_ 00000_ 00000_ 0000', '']
?                                       ++++


----------------------------------------------------------------------
Ran 21 tests in 169.371s

FAILED (failures=1)
Test failed: <unittest.runner.TextTestResult run=21 errors=0 failures=1>
Falsifying example: test_to_dataframe(self=<tests_ieee.TestIEEE testMethod=test_to_dataframe>, entry={'abstract': '00000',
 'affiliations': '00000',
 'authors': ['000/0', '00000', '00001', '00/00', '0/000'],
 'doi': '00000',
 'epage': '',
 'issn': '00000',
 'mdurl': '00000',
 'partnum': '00000',
 'pdf': '00000',
 'publicationId': '00000',
 'publisher': '00000',
 'pubtitle': '00000',
 'punumber': '00000',
 'py': datetime.date(2000, 1, 1),
 'spage': '',
 'term': [',0000', '00000', '00000', '00000', '0000,'],
 'title': '00000'})
You can add @seed(302934307671667531413257853548643485645) to this test to reproduce this failure.
```

Any ideas what we can do about this?

**Comment by drvinceknight** [comment]
This could be due to an update of hypothesis. On Axelrod we strictly pinned hypothesis to `3.2` as a result: https://github.com/Axelrod-Python/Axelrod/pull/1130/commits/4341ed841a1ccdd1ec1dfdbd749e98cb14d68360

**Comment by TheChymera** [comment]
Could you update your usage of hypothesis? The main Gentoo tree only offers access to hypothesis `3.6.0` and `3.31.1`. It seems like `3.2` was deprecated quite a while ago, and generally devs don't want to bring deprecated stuff back.

**Comment by drvinceknight** [comment]
`3.31.1` might well work fine. Either way I'd recommend strict pinning Hypothesis. In the past I've spent a lot of time hunting things down due to their upstream changes.

**Comment by TheChymera** [comment]
Ok, it seems this issue is indeed hypothesis related, but I am only experiencing it while testing with hypothesis `3.31.1`, under with `3.6.0` all tests pass.

So I guess I can close this now, but I would recommend you bump your hypothesis API usage to the newest stable version.

**Comment by TheChymera** [comment]
Arcas should soon be available on Gentoo https://github.com/gentoo/sci/pull/821
